---
name: nginx-varnish

services:
  nginx-varnish:
    image: atompi/nginx-varnish:1.26.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/core.d:/etc/nginx/core.d
      - ./conf/nginx/ssl.d:/etc/nginx/ssl.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/varnish/default.vcl:/etc/varnish/default.vcl
      - ./logs/nginx:/var/log/nginx
      - ./logs/varnish:/var/log/varnish
      - ./data/nginx:/data

networks:
  default:
    external: true
    name: compose
